theme: congo
languageCode: en-US
defaultContentLanguage: en
title: Samrit Pramanik
enableEmoji: yes
summaryLength: 30
author:
  bio: 'This is Samrit Pramanik'
  image: img/pic.jpg
  links:
    - twitter: https://twitter.com/Samrit2442
    - facebook: https://www.facebook.com/samrit.pramanik24ps
    - linkedin: https://www.linkedin.com/in/samritpramanik24/
    - youtube: https://youtube.com/
  name: Samrit Pramanik
taxonomies:
  tag: tags
params:
  article:
    editAppendPath: yes
    editURL: https://github.com/jpanther/congo/tree/dev/exampleSite/content/
    showBreadcrumbs: yes
    showEdit: yes
  homepage:
    layout: custom
    mainSections: samples
    showRecent: yes
  list:
    groupByYear: no
    showBreadcrumbs: yes
menu:
  main:
    - name: Docs
      pageRef: docs
      weight: 10
    - name: Samples
      pageRef: samples
      weight: 20
    - name: Users
      pageRef: users
      weight: 30
    - name: GitHub
      url: https://github.com/jpanther/congo
      weight: 40
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    noClasses: no
